data = [
  { "name": "Mari Vanna DC" , "img_url": "http://www.danielswartz.com/revampdotcom/2240/5.jpg", "lat": "38.905189", "lng": "-77.040467", "description": "A place to party in Russian fashion or just enjoy a quiet dinner. The decoration is inspired in traditional Russian households, the kind of stuff you find when you visit your babushka, if your grandma were Russian. Upstairs you will find a lounge bar were you can dance to post-Soviet pop while enjoying classic cartoons drowned in a vodka cocktail.", "web_url":"http://www.marivanna.ru/washington/" },

  { "name": "Maddy's Tap Room", "img_url": "http://www.rpharchitecture.com/wp-content/uploads/2014/09/DSC_3324_co.jpg", "lat": "38.908491", "lng": "-77.042327", "description": "An affordable stop for local beer lovers.", "web_url": "http://maddystaproom.com/" },

  { "name": "The Big Hunt", "img_url": "http://voices.washingtonpost.com/goingoutgurus/454DF10_5.13_GOG_BigHunt-111.jpg", "lat":  "38.920014", "lng": "-76.986281", "description": "Craft beer in DC is quite the thing right now. An affordable, low-key place to try plenty of them is The Big Hunt. This is also one of the oldest bars in DC.", "web_url": "http://thebighunt.net/"},

  { "name": "The Saloon", "img_url": "https://s3-media1.fl.yelpcdn.com/bphoto/YCRSPd0ibnQzx8H63jQDoQ/o.jpg", "lat": "38.917194", "lng": "-77.028522", "description": "No TVs, no loud music, no phones allowed. This is a place where you have to follow some rules if you want to be served, but it is a worth tradeoff: they have an impressive selection of beers and moonshines." , "web_url": "None" },

  { "name": "The Petersen House (where Lincoln died)", "img_url": "https://fordstheatre.files.wordpress.com/2016/08/phbackparlor.jpg", "lat": "38.896767" , "lng": "-77.026294", "description": "The Petersen House (House Where Lincoln Died) at 516 10th street was the home of William and Anna Petersen. On the night of April 14, 1865 the mortally wounded president was carried to a back bedroom in this house. The Petersen family aided as they could, although on this night their home was no longer their own. Over 90 people would come and go through the house to pay their last respects to the dying president. Soldiers stood guard at the front door and were posted on the roof to keep the growing crowds at bay. While doctors cared for the president the Petersen family and some of the boarders spent the night in the basement. At 7:22 am, April 15, 1865, Abraham Lincoln died in the back bedroom of this humble house.", "web_url":"http://www.fords.org/home/plan-your-visit/daytime-visits-fords-theatre/petersen-house" },

  { "name": "The C&O Canal", "img_url": "https://s3-media2.fl.yelpcdn.com/bphoto/My_suartYfttAaGiVFu9tw/o.jpg", "lat": "38.904308", "lng": "-77.059972", "description": "Preserving America's early transportation history, the C&O Canal began as a dream of passage to Western wealth. Operating for nearly 100 years the canal was a lifeline for communities along the Potomac River as coal, lumber and agricultural products floated down the waterway to market. Today it endures as a pathway for discovering historical, natural and recreational treasures!", "web_url": "https://www.nps.gov/choh/index.htm" },

  { "name": "Dupont Underground", "img_url": "http://cdnassets.hw.net/dims4/GG/58a0212/2147483647/resize/876x%3E/quality/90/?url=http%3A%2F%2Fcdnassets.hw.net%2F48%2F30%2F2fa3f91541929ed2abdbd8749931%2Fhoudesousa-raise-raze-01.jpg", "lat": "38.916120", "lng": "-77.042738", "description": "The Dupont Underground is transforming a forgotten space beneath Washington, D.C.’s iconic Dupont Circle into a cultural destination. Opened in 1949 as a trolley station, 75,000 s.f. of underground platforms and tunnels were closed off in 1962, when the city’s streetcar system shut down. Other than designation as fallout shelter in the late 1960s and hosting a short-lived food court on the west platform in the mid-1990s, the space has remained empty. Until now.", "web_url": "http://www.dupontunderground.org/" },

  { "name": "National Arboretum", "img_url": "http://packedsuitcase.com/wp-content/uploads/2014/04/National-Arboretum-Capitol-Columns-reflection-600x600.jpg", "lat": "38.912340", "lng": "-76.969921", "description": "The National Arboretum is huge and interesting all times of the year. It seems the best times are spring and into early summer to see the dogwoods, azaleas, camellias etc. But anytime is the time to see the amazing Bonsai collection, and the Gotelli Conifer collection. If you love plants and beauty it is a wonderful place.", "web_url": "http://www.usna.usda.gov/" }
]
